// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_protos.proto

package org.utkuozdemir.sample1.protobuf;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.utkuozdemir.sample1.protobuf.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string firstLine = 1;</code>
   */
  boolean hasFirstLine();
  /**
   * <code>required string firstLine = 1;</code>
   */
  java.lang.String getFirstLine();
  /**
   * <code>required string firstLine = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstLineBytes();

  /**
   * <code>optional string secondLine = 2;</code>
   */
  boolean hasSecondLine();
  /**
   * <code>optional string secondLine = 2;</code>
   */
  java.lang.String getSecondLine();
  /**
   * <code>optional string secondLine = 2;</code>
   */
  com.google.protobuf.ByteString
      getSecondLineBytes();

  /**
   * <code>optional uint32 postalCode = 3;</code>
   */
  boolean hasPostalCode();
  /**
   * <code>optional uint32 postalCode = 3;</code>
   */
  int getPostalCode();
}
