// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_protos.proto

package org.utkuozdemir.sample1.protobuf;

/**
 * Protobuf type {@code org.utkuozdemir.sample1.protobuf.Address}
 */
public final class Address extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.utkuozdemir.sample1.protobuf.Address)
    AddressOrBuilder {
  // Use Address.newBuilder() to construct.
  private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Address(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Address defaultInstance;
  public static Address getDefaultInstance() {
    return defaultInstance;
  }

  public Address getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Address(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            firstLine_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            secondLine_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            postalCode_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Address_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Address_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.utkuozdemir.sample1.protobuf.Address.class, org.utkuozdemir.sample1.protobuf.Address.Builder.class);
  }

  public static com.google.protobuf.Parser<Address> PARSER =
      new com.google.protobuf.AbstractParser<Address>() {
    public Address parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Address(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Address> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int FIRSTLINE_FIELD_NUMBER = 1;
  private java.lang.Object firstLine_;
  /**
   * <code>required string firstLine = 1;</code>
   */
  public boolean hasFirstLine() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string firstLine = 1;</code>
   */
  public java.lang.String getFirstLine() {
    java.lang.Object ref = firstLine_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        firstLine_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string firstLine = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFirstLineBytes() {
    java.lang.Object ref = firstLine_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstLine_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECONDLINE_FIELD_NUMBER = 2;
  private java.lang.Object secondLine_;
  /**
   * <code>optional string secondLine = 2;</code>
   */
  public boolean hasSecondLine() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string secondLine = 2;</code>
   */
  public java.lang.String getSecondLine() {
    java.lang.Object ref = secondLine_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        secondLine_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string secondLine = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSecondLineBytes() {
    java.lang.Object ref = secondLine_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secondLine_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTALCODE_FIELD_NUMBER = 3;
  private int postalCode_;
  /**
   * <code>optional uint32 postalCode = 3;</code>
   */
  public boolean hasPostalCode() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional uint32 postalCode = 3;</code>
   */
  public int getPostalCode() {
    return postalCode_;
  }

  private void initFields() {
    firstLine_ = "";
    secondLine_ = "";
    postalCode_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasFirstLine()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getFirstLineBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSecondLineBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt32(3, postalCode_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getFirstLineBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSecondLineBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, postalCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.utkuozdemir.sample1.protobuf.Address parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.utkuozdemir.sample1.protobuf.Address prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.utkuozdemir.sample1.protobuf.Address}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.utkuozdemir.sample1.protobuf.Address)
      org.utkuozdemir.sample1.protobuf.AddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.utkuozdemir.sample1.protobuf.Address.class, org.utkuozdemir.sample1.protobuf.Address.Builder.class);
    }

    // Construct using org.utkuozdemir.sample1.protobuf.Address.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      firstLine_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      secondLine_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      postalCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Address_descriptor;
    }

    public org.utkuozdemir.sample1.protobuf.Address getDefaultInstanceForType() {
      return org.utkuozdemir.sample1.protobuf.Address.getDefaultInstance();
    }

    public org.utkuozdemir.sample1.protobuf.Address build() {
      org.utkuozdemir.sample1.protobuf.Address result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.utkuozdemir.sample1.protobuf.Address buildPartial() {
      org.utkuozdemir.sample1.protobuf.Address result = new org.utkuozdemir.sample1.protobuf.Address(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.firstLine_ = firstLine_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.secondLine_ = secondLine_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.postalCode_ = postalCode_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.utkuozdemir.sample1.protobuf.Address) {
        return mergeFrom((org.utkuozdemir.sample1.protobuf.Address)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.utkuozdemir.sample1.protobuf.Address other) {
      if (other == org.utkuozdemir.sample1.protobuf.Address.getDefaultInstance()) return this;
      if (other.hasFirstLine()) {
        bitField0_ |= 0x00000001;
        firstLine_ = other.firstLine_;
        onChanged();
      }
      if (other.hasSecondLine()) {
        bitField0_ |= 0x00000002;
        secondLine_ = other.secondLine_;
        onChanged();
      }
      if (other.hasPostalCode()) {
        setPostalCode(other.getPostalCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasFirstLine()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.utkuozdemir.sample1.protobuf.Address parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.utkuozdemir.sample1.protobuf.Address) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object firstLine_ = "";
    /**
     * <code>required string firstLine = 1;</code>
     */
    public boolean hasFirstLine() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string firstLine = 1;</code>
     */
    public java.lang.String getFirstLine() {
      java.lang.Object ref = firstLine_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstLine_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string firstLine = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstLineBytes() {
      java.lang.Object ref = firstLine_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstLine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string firstLine = 1;</code>
     */
    public Builder setFirstLine(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      firstLine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string firstLine = 1;</code>
     */
    public Builder clearFirstLine() {
      bitField0_ = (bitField0_ & ~0x00000001);
      firstLine_ = getDefaultInstance().getFirstLine();
      onChanged();
      return this;
    }
    /**
     * <code>required string firstLine = 1;</code>
     */
    public Builder setFirstLineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      firstLine_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object secondLine_ = "";
    /**
     * <code>optional string secondLine = 2;</code>
     */
    public boolean hasSecondLine() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string secondLine = 2;</code>
     */
    public java.lang.String getSecondLine() {
      java.lang.Object ref = secondLine_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          secondLine_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string secondLine = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSecondLineBytes() {
      java.lang.Object ref = secondLine_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secondLine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string secondLine = 2;</code>
     */
    public Builder setSecondLine(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      secondLine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string secondLine = 2;</code>
     */
    public Builder clearSecondLine() {
      bitField0_ = (bitField0_ & ~0x00000002);
      secondLine_ = getDefaultInstance().getSecondLine();
      onChanged();
      return this;
    }
    /**
     * <code>optional string secondLine = 2;</code>
     */
    public Builder setSecondLineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      secondLine_ = value;
      onChanged();
      return this;
    }

    private int postalCode_ ;
    /**
     * <code>optional uint32 postalCode = 3;</code>
     */
    public boolean hasPostalCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 postalCode = 3;</code>
     */
    public int getPostalCode() {
      return postalCode_;
    }
    /**
     * <code>optional uint32 postalCode = 3;</code>
     */
    public Builder setPostalCode(int value) {
      bitField0_ |= 0x00000004;
      postalCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 postalCode = 3;</code>
     */
    public Builder clearPostalCode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      postalCode_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.utkuozdemir.sample1.protobuf.Address)
  }

  static {
    defaultInstance = new Address(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.utkuozdemir.sample1.protobuf.Address)
}

