// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_protos.proto

package org.utkuozdemir.sample1.protobuf;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_utkuozdemir_sample1_protobuf_Address_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_utkuozdemir_sample1_protobuf_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_utkuozdemir_sample1_protobuf_Person_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_utkuozdemir_sample1_protobuf_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023person_protos.proto\022 org.utkuozdemir.s" +
      "ample1.protobuf\"D\n\007Address\022\021\n\tfirstLine\030" +
      "\001 \002(\t\022\022\n\nsecondLine\030\002 \001(\t\022\022\n\npostalCode\030" +
      "\003 \001(\r\"\302\001\n\006Person\022\021\n\tfirstName\030\001 \002(\t\022\020\n\010l" +
      "astName\030\002 \002(\t\022\013\n\003age\030\003 \002(\r\022\016\n\006active\030\004 \002" +
      "(\010\0228\n\006gender\030\005 \001(\0162(.org.utkuozdemir.sam" +
      "ple1.protobuf.Gender\022<\n\taddresses\030\006 \003(\0132" +
      ").org.utkuozdemir.sample1.protobuf.Addre" +
      "ss*\036\n\006Gender\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\002B$\n or" +
      "g.utkuozdemir.sample1.protobufP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_utkuozdemir_sample1_protobuf_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_utkuozdemir_sample1_protobuf_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_utkuozdemir_sample1_protobuf_Address_descriptor,
        new java.lang.String[] { "FirstLine", "SecondLine", "PostalCode", });
    internal_static_org_utkuozdemir_sample1_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_utkuozdemir_sample1_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_utkuozdemir_sample1_protobuf_Person_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Age", "Active", "Gender", "Addresses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
