// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_protos.proto

package org.utkuozdemir.sample1.protobuf;

/**
 * Protobuf type {@code org.utkuozdemir.sample1.protobuf.Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.utkuozdemir.sample1.protobuf.Person)
    PersonOrBuilder {
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Person defaultInstance;
  public static Person getDefaultInstance() {
    return defaultInstance;
  }

  public Person getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            firstName_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            lastName_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            age_ = input.readUInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            active_ = input.readBool();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();
            org.utkuozdemir.sample1.protobuf.Gender value = org.utkuozdemir.sample1.protobuf.Gender.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(5, rawValue);
            } else {
              bitField0_ |= 0x00000010;
              gender_ = value;
            }
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              addresses_ = new java.util.ArrayList<org.utkuozdemir.sample1.protobuf.Address>();
              mutable_bitField0_ |= 0x00000020;
            }
            addresses_.add(input.readMessage(org.utkuozdemir.sample1.protobuf.Address.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        addresses_ = java.util.Collections.unmodifiableList(addresses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Person_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.utkuozdemir.sample1.protobuf.Person.class, org.utkuozdemir.sample1.protobuf.Person.Builder.class);
  }

  public static com.google.protobuf.Parser<Person> PARSER =
      new com.google.protobuf.AbstractParser<Person>() {
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int FIRSTNAME_FIELD_NUMBER = 1;
  private java.lang.Object firstName_;
  /**
   * <code>required string firstName = 1;</code>
   */
  public boolean hasFirstName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string firstName = 1;</code>
   */
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        firstName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string firstName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 2;
  private java.lang.Object lastName_;
  /**
   * <code>required string lastName = 2;</code>
   */
  public boolean hasLastName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string lastName = 2;</code>
   */
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        lastName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string lastName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 3;
  private int age_;
  /**
   * <code>required uint32 age = 3;</code>
   */
  public boolean hasAge() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required uint32 age = 3;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int ACTIVE_FIELD_NUMBER = 4;
  private boolean active_;
  /**
   * <code>required bool active = 4;</code>
   */
  public boolean hasActive() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required bool active = 4;</code>
   */
  public boolean getActive() {
    return active_;
  }

  public static final int GENDER_FIELD_NUMBER = 5;
  private org.utkuozdemir.sample1.protobuf.Gender gender_;
  /**
   * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
   */
  public boolean hasGender() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
   */
  public org.utkuozdemir.sample1.protobuf.Gender getGender() {
    return gender_;
  }

  public static final int ADDRESSES_FIELD_NUMBER = 6;
  private java.util.List<org.utkuozdemir.sample1.protobuf.Address> addresses_;
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  public java.util.List<org.utkuozdemir.sample1.protobuf.Address> getAddressesList() {
    return addresses_;
  }
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  public java.util.List<? extends org.utkuozdemir.sample1.protobuf.AddressOrBuilder> 
      getAddressesOrBuilderList() {
    return addresses_;
  }
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  public int getAddressesCount() {
    return addresses_.size();
  }
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  public org.utkuozdemir.sample1.protobuf.Address getAddresses(int index) {
    return addresses_.get(index);
  }
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  public org.utkuozdemir.sample1.protobuf.AddressOrBuilder getAddressesOrBuilder(
      int index) {
    return addresses_.get(index);
  }

  private void initFields() {
    firstName_ = "";
    lastName_ = "";
    age_ = 0;
    active_ = false;
    gender_ = org.utkuozdemir.sample1.protobuf.Gender.MALE;
    addresses_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasFirstName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLastName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAge()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasActive()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getAddressesCount(); i++) {
      if (!getAddresses(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getFirstNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getLastNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt32(3, age_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBool(4, active_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeEnum(5, gender_.getNumber());
    }
    for (int i = 0; i < addresses_.size(); i++) {
      output.writeMessage(6, addresses_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getFirstNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getLastNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, age_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, active_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, gender_.getNumber());
    }
    for (int i = 0; i < addresses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, addresses_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.utkuozdemir.sample1.protobuf.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.utkuozdemir.sample1.protobuf.Person prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.utkuozdemir.sample1.protobuf.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.utkuozdemir.sample1.protobuf.Person)
      org.utkuozdemir.sample1.protobuf.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.utkuozdemir.sample1.protobuf.Person.class, org.utkuozdemir.sample1.protobuf.Person.Builder.class);
    }

    // Construct using org.utkuozdemir.sample1.protobuf.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getAddressesFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      firstName_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      lastName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      age_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      active_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      gender_ = org.utkuozdemir.sample1.protobuf.Gender.MALE;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (addressesBuilder_ == null) {
        addresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        addressesBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.utkuozdemir.sample1.protobuf.PersonProtos.internal_static_org_utkuozdemir_sample1_protobuf_Person_descriptor;
    }

    public org.utkuozdemir.sample1.protobuf.Person getDefaultInstanceForType() {
      return org.utkuozdemir.sample1.protobuf.Person.getDefaultInstance();
    }

    public org.utkuozdemir.sample1.protobuf.Person build() {
      org.utkuozdemir.sample1.protobuf.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.utkuozdemir.sample1.protobuf.Person buildPartial() {
      org.utkuozdemir.sample1.protobuf.Person result = new org.utkuozdemir.sample1.protobuf.Person(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.firstName_ = firstName_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.lastName_ = lastName_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.age_ = age_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.active_ = active_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.gender_ = gender_;
      if (addressesBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          addresses_ = java.util.Collections.unmodifiableList(addresses_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.addresses_ = addresses_;
      } else {
        result.addresses_ = addressesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.utkuozdemir.sample1.protobuf.Person) {
        return mergeFrom((org.utkuozdemir.sample1.protobuf.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.utkuozdemir.sample1.protobuf.Person other) {
      if (other == org.utkuozdemir.sample1.protobuf.Person.getDefaultInstance()) return this;
      if (other.hasFirstName()) {
        bitField0_ |= 0x00000001;
        firstName_ = other.firstName_;
        onChanged();
      }
      if (other.hasLastName()) {
        bitField0_ |= 0x00000002;
        lastName_ = other.lastName_;
        onChanged();
      }
      if (other.hasAge()) {
        setAge(other.getAge());
      }
      if (other.hasActive()) {
        setActive(other.getActive());
      }
      if (other.hasGender()) {
        setGender(other.getGender());
      }
      if (addressesBuilder_ == null) {
        if (!other.addresses_.isEmpty()) {
          if (addresses_.isEmpty()) {
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureAddressesIsMutable();
            addresses_.addAll(other.addresses_);
          }
          onChanged();
        }
      } else {
        if (!other.addresses_.isEmpty()) {
          if (addressesBuilder_.isEmpty()) {
            addressesBuilder_.dispose();
            addressesBuilder_ = null;
            addresses_ = other.addresses_;
            bitField0_ = (bitField0_ & ~0x00000020);
            addressesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAddressesFieldBuilder() : null;
          } else {
            addressesBuilder_.addAllMessages(other.addresses_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasFirstName()) {
        
        return false;
      }
      if (!hasLastName()) {
        
        return false;
      }
      if (!hasAge()) {
        
        return false;
      }
      if (!hasActive()) {
        
        return false;
      }
      for (int i = 0; i < getAddressesCount(); i++) {
        if (!getAddresses(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.utkuozdemir.sample1.protobuf.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.utkuozdemir.sample1.protobuf.Person) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object firstName_ = "";
    /**
     * <code>required string firstName = 1;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string firstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string firstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string firstName = 1;</code>
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string firstName = 1;</code>
     */
    public Builder clearFirstName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>required string firstName = 1;</code>
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>required string lastName = 2;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string lastName = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string lastName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string lastName = 2;</code>
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string lastName = 2;</code>
     */
    public Builder clearLastName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>required string lastName = 2;</code>
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      lastName_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>required uint32 age = 3;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>required uint32 age = 3;</code>
     */
    public Builder setAge(int value) {
      bitField0_ |= 0x00000004;
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 age = 3;</code>
     */
    public Builder clearAge() {
      bitField0_ = (bitField0_ & ~0x00000004);
      age_ = 0;
      onChanged();
      return this;
    }

    private boolean active_ ;
    /**
     * <code>required bool active = 4;</code>
     */
    public boolean hasActive() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool active = 4;</code>
     */
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>required bool active = 4;</code>
     */
    public Builder setActive(boolean value) {
      bitField0_ |= 0x00000008;
      active_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool active = 4;</code>
     */
    public Builder clearActive() {
      bitField0_ = (bitField0_ & ~0x00000008);
      active_ = false;
      onChanged();
      return this;
    }

    private org.utkuozdemir.sample1.protobuf.Gender gender_ = org.utkuozdemir.sample1.protobuf.Gender.MALE;
    /**
     * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
     */
    public org.utkuozdemir.sample1.protobuf.Gender getGender() {
      return gender_;
    }
    /**
     * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
     */
    public Builder setGender(org.utkuozdemir.sample1.protobuf.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
     */
    public Builder clearGender() {
      bitField0_ = (bitField0_ & ~0x00000010);
      gender_ = org.utkuozdemir.sample1.protobuf.Gender.MALE;
      onChanged();
      return this;
    }

    private java.util.List<org.utkuozdemir.sample1.protobuf.Address> addresses_ =
      java.util.Collections.emptyList();
    private void ensureAddressesIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        addresses_ = new java.util.ArrayList<org.utkuozdemir.sample1.protobuf.Address>(addresses_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.utkuozdemir.sample1.protobuf.Address, org.utkuozdemir.sample1.protobuf.Address.Builder, org.utkuozdemir.sample1.protobuf.AddressOrBuilder> addressesBuilder_;

    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public java.util.List<org.utkuozdemir.sample1.protobuf.Address> getAddressesList() {
      if (addressesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(addresses_);
      } else {
        return addressesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public int getAddressesCount() {
      if (addressesBuilder_ == null) {
        return addresses_.size();
      } else {
        return addressesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public org.utkuozdemir.sample1.protobuf.Address getAddresses(int index) {
      if (addressesBuilder_ == null) {
        return addresses_.get(index);
      } else {
        return addressesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder setAddresses(
        int index, org.utkuozdemir.sample1.protobuf.Address value) {
      if (addressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressesIsMutable();
        addresses_.set(index, value);
        onChanged();
      } else {
        addressesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder setAddresses(
        int index, org.utkuozdemir.sample1.protobuf.Address.Builder builderForValue) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.set(index, builderForValue.build());
        onChanged();
      } else {
        addressesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder addAddresses(org.utkuozdemir.sample1.protobuf.Address value) {
      if (addressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressesIsMutable();
        addresses_.add(value);
        onChanged();
      } else {
        addressesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder addAddresses(
        int index, org.utkuozdemir.sample1.protobuf.Address value) {
      if (addressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressesIsMutable();
        addresses_.add(index, value);
        onChanged();
      } else {
        addressesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder addAddresses(
        org.utkuozdemir.sample1.protobuf.Address.Builder builderForValue) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.add(builderForValue.build());
        onChanged();
      } else {
        addressesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder addAddresses(
        int index, org.utkuozdemir.sample1.protobuf.Address.Builder builderForValue) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.add(index, builderForValue.build());
        onChanged();
      } else {
        addressesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder addAllAddresses(
        java.lang.Iterable<? extends org.utkuozdemir.sample1.protobuf.Address> values) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addresses_);
        onChanged();
      } else {
        addressesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder clearAddresses() {
      if (addressesBuilder_ == null) {
        addresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        addressesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public Builder removeAddresses(int index) {
      if (addressesBuilder_ == null) {
        ensureAddressesIsMutable();
        addresses_.remove(index);
        onChanged();
      } else {
        addressesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public org.utkuozdemir.sample1.protobuf.Address.Builder getAddressesBuilder(
        int index) {
      return getAddressesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public org.utkuozdemir.sample1.protobuf.AddressOrBuilder getAddressesOrBuilder(
        int index) {
      if (addressesBuilder_ == null) {
        return addresses_.get(index);  } else {
        return addressesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public java.util.List<? extends org.utkuozdemir.sample1.protobuf.AddressOrBuilder> 
         getAddressesOrBuilderList() {
      if (addressesBuilder_ != null) {
        return addressesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(addresses_);
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public org.utkuozdemir.sample1.protobuf.Address.Builder addAddressesBuilder() {
      return getAddressesFieldBuilder().addBuilder(
          org.utkuozdemir.sample1.protobuf.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public org.utkuozdemir.sample1.protobuf.Address.Builder addAddressesBuilder(
        int index) {
      return getAddressesFieldBuilder().addBuilder(
          index, org.utkuozdemir.sample1.protobuf.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
     */
    public java.util.List<org.utkuozdemir.sample1.protobuf.Address.Builder> 
         getAddressesBuilderList() {
      return getAddressesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.utkuozdemir.sample1.protobuf.Address, org.utkuozdemir.sample1.protobuf.Address.Builder, org.utkuozdemir.sample1.protobuf.AddressOrBuilder> 
        getAddressesFieldBuilder() {
      if (addressesBuilder_ == null) {
        addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.utkuozdemir.sample1.protobuf.Address, org.utkuozdemir.sample1.protobuf.Address.Builder, org.utkuozdemir.sample1.protobuf.AddressOrBuilder>(
                addresses_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        addresses_ = null;
      }
      return addressesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.utkuozdemir.sample1.protobuf.Person)
  }

  static {
    defaultInstance = new Person(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.utkuozdemir.sample1.protobuf.Person)
}

