// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_protos.proto

package org.utkuozdemir.sample1.protobuf;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.utkuozdemir.sample1.protobuf.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string firstName = 1;</code>
   */
  boolean hasFirstName();
  /**
   * <code>required string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>required string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>required string lastName = 2;</code>
   */
  boolean hasLastName();
  /**
   * <code>required string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>required string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>required uint32 age = 3;</code>
   */
  boolean hasAge();
  /**
   * <code>required uint32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>required bool active = 4;</code>
   */
  boolean hasActive();
  /**
   * <code>required bool active = 4;</code>
   */
  boolean getActive();

  /**
   * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
   */
  boolean hasGender();
  /**
   * <code>optional .org.utkuozdemir.sample1.protobuf.Gender gender = 5;</code>
   */
  org.utkuozdemir.sample1.protobuf.Gender getGender();

  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  java.util.List<org.utkuozdemir.sample1.protobuf.Address> 
      getAddressesList();
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  org.utkuozdemir.sample1.protobuf.Address getAddresses(int index);
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  int getAddressesCount();
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  java.util.List<? extends org.utkuozdemir.sample1.protobuf.AddressOrBuilder> 
      getAddressesOrBuilderList();
  /**
   * <code>repeated .org.utkuozdemir.sample1.protobuf.Address addresses = 6;</code>
   */
  org.utkuozdemir.sample1.protobuf.AddressOrBuilder getAddressesOrBuilder(
      int index);
}
