// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: one_protos.proto

package org.utkuozdemir.sample2.protobuf;

public interface ManyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.utkuozdemir.sample2.protobuf.Many)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
