// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: one_protos.proto

package org.utkuozdemir.sample2.protobuf;

/**
 * Protobuf type {@code org.utkuozdemir.sample2.protobuf.One}
 */
public final class One extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.utkuozdemir.sample2.protobuf.One)
    OneOrBuilder {
  // Use One.newBuilder() to construct.
  private One(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private One(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final One defaultInstance;
  public static One getDefaultInstance() {
    return defaultInstance;
  }

  public One getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private One(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            name_ = bs;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              many_ = new java.util.ArrayList<org.utkuozdemir.sample2.protobuf.Many>();
              mutable_bitField0_ |= 0x00000002;
            }
            many_.add(input.readMessage(org.utkuozdemir.sample2.protobuf.Many.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        many_ = java.util.Collections.unmodifiableList(many_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.utkuozdemir.sample2.protobuf.OneProtos.internal_static_org_utkuozdemir_sample2_protobuf_One_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.utkuozdemir.sample2.protobuf.OneProtos.internal_static_org_utkuozdemir_sample2_protobuf_One_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.utkuozdemir.sample2.protobuf.One.class, org.utkuozdemir.sample2.protobuf.One.Builder.class);
  }

  public static com.google.protobuf.Parser<One> PARSER =
      new com.google.protobuf.AbstractParser<One>() {
    public One parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new One(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<One> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>required string name = 1;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MANY_FIELD_NUMBER = 2;
  private java.util.List<org.utkuozdemir.sample2.protobuf.Many> many_;
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  public java.util.List<org.utkuozdemir.sample2.protobuf.Many> getManyList() {
    return many_;
  }
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  public java.util.List<? extends org.utkuozdemir.sample2.protobuf.ManyOrBuilder> 
      getManyOrBuilderList() {
    return many_;
  }
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  public int getManyCount() {
    return many_.size();
  }
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  public org.utkuozdemir.sample2.protobuf.Many getMany(int index) {
    return many_.get(index);
  }
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  public org.utkuozdemir.sample2.protobuf.ManyOrBuilder getManyOrBuilder(
      int index) {
    return many_.get(index);
  }

  private void initFields() {
    name_ = "";
    many_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getManyCount(); i++) {
      if (!getMany(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    for (int i = 0; i < many_.size(); i++) {
      output.writeMessage(2, many_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    for (int i = 0; i < many_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, many_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.utkuozdemir.sample2.protobuf.One parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.utkuozdemir.sample2.protobuf.One parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.utkuozdemir.sample2.protobuf.One prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.utkuozdemir.sample2.protobuf.One}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.utkuozdemir.sample2.protobuf.One)
      org.utkuozdemir.sample2.protobuf.OneOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.utkuozdemir.sample2.protobuf.OneProtos.internal_static_org_utkuozdemir_sample2_protobuf_One_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.utkuozdemir.sample2.protobuf.OneProtos.internal_static_org_utkuozdemir_sample2_protobuf_One_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.utkuozdemir.sample2.protobuf.One.class, org.utkuozdemir.sample2.protobuf.One.Builder.class);
    }

    // Construct using org.utkuozdemir.sample2.protobuf.One.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getManyFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (manyBuilder_ == null) {
        many_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        manyBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.utkuozdemir.sample2.protobuf.OneProtos.internal_static_org_utkuozdemir_sample2_protobuf_One_descriptor;
    }

    public org.utkuozdemir.sample2.protobuf.One getDefaultInstanceForType() {
      return org.utkuozdemir.sample2.protobuf.One.getDefaultInstance();
    }

    public org.utkuozdemir.sample2.protobuf.One build() {
      org.utkuozdemir.sample2.protobuf.One result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.utkuozdemir.sample2.protobuf.One buildPartial() {
      org.utkuozdemir.sample2.protobuf.One result = new org.utkuozdemir.sample2.protobuf.One(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (manyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          many_ = java.util.Collections.unmodifiableList(many_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.many_ = many_;
      } else {
        result.many_ = manyBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.utkuozdemir.sample2.protobuf.One) {
        return mergeFrom((org.utkuozdemir.sample2.protobuf.One)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.utkuozdemir.sample2.protobuf.One other) {
      if (other == org.utkuozdemir.sample2.protobuf.One.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (manyBuilder_ == null) {
        if (!other.many_.isEmpty()) {
          if (many_.isEmpty()) {
            many_ = other.many_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureManyIsMutable();
            many_.addAll(other.many_);
          }
          onChanged();
        }
      } else {
        if (!other.many_.isEmpty()) {
          if (manyBuilder_.isEmpty()) {
            manyBuilder_.dispose();
            manyBuilder_ = null;
            many_ = other.many_;
            bitField0_ = (bitField0_ & ~0x00000002);
            manyBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getManyFieldBuilder() : null;
          } else {
            manyBuilder_.addAllMessages(other.many_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasName()) {
        
        return false;
      }
      for (int i = 0; i < getManyCount(); i++) {
        if (!getMany(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.utkuozdemir.sample2.protobuf.One parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.utkuozdemir.sample2.protobuf.One) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.utkuozdemir.sample2.protobuf.Many> many_ =
      java.util.Collections.emptyList();
    private void ensureManyIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        many_ = new java.util.ArrayList<org.utkuozdemir.sample2.protobuf.Many>(many_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.utkuozdemir.sample2.protobuf.Many, org.utkuozdemir.sample2.protobuf.Many.Builder, org.utkuozdemir.sample2.protobuf.ManyOrBuilder> manyBuilder_;

    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public java.util.List<org.utkuozdemir.sample2.protobuf.Many> getManyList() {
      if (manyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(many_);
      } else {
        return manyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public int getManyCount() {
      if (manyBuilder_ == null) {
        return many_.size();
      } else {
        return manyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public org.utkuozdemir.sample2.protobuf.Many getMany(int index) {
      if (manyBuilder_ == null) {
        return many_.get(index);
      } else {
        return manyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder setMany(
        int index, org.utkuozdemir.sample2.protobuf.Many value) {
      if (manyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManyIsMutable();
        many_.set(index, value);
        onChanged();
      } else {
        manyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder setMany(
        int index, org.utkuozdemir.sample2.protobuf.Many.Builder builderForValue) {
      if (manyBuilder_ == null) {
        ensureManyIsMutable();
        many_.set(index, builderForValue.build());
        onChanged();
      } else {
        manyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder addMany(org.utkuozdemir.sample2.protobuf.Many value) {
      if (manyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManyIsMutable();
        many_.add(value);
        onChanged();
      } else {
        manyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder addMany(
        int index, org.utkuozdemir.sample2.protobuf.Many value) {
      if (manyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManyIsMutable();
        many_.add(index, value);
        onChanged();
      } else {
        manyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder addMany(
        org.utkuozdemir.sample2.protobuf.Many.Builder builderForValue) {
      if (manyBuilder_ == null) {
        ensureManyIsMutable();
        many_.add(builderForValue.build());
        onChanged();
      } else {
        manyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder addMany(
        int index, org.utkuozdemir.sample2.protobuf.Many.Builder builderForValue) {
      if (manyBuilder_ == null) {
        ensureManyIsMutable();
        many_.add(index, builderForValue.build());
        onChanged();
      } else {
        manyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder addAllMany(
        java.lang.Iterable<? extends org.utkuozdemir.sample2.protobuf.Many> values) {
      if (manyBuilder_ == null) {
        ensureManyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, many_);
        onChanged();
      } else {
        manyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder clearMany() {
      if (manyBuilder_ == null) {
        many_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        manyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public Builder removeMany(int index) {
      if (manyBuilder_ == null) {
        ensureManyIsMutable();
        many_.remove(index);
        onChanged();
      } else {
        manyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public org.utkuozdemir.sample2.protobuf.Many.Builder getManyBuilder(
        int index) {
      return getManyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public org.utkuozdemir.sample2.protobuf.ManyOrBuilder getManyOrBuilder(
        int index) {
      if (manyBuilder_ == null) {
        return many_.get(index);  } else {
        return manyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public java.util.List<? extends org.utkuozdemir.sample2.protobuf.ManyOrBuilder> 
         getManyOrBuilderList() {
      if (manyBuilder_ != null) {
        return manyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(many_);
      }
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public org.utkuozdemir.sample2.protobuf.Many.Builder addManyBuilder() {
      return getManyFieldBuilder().addBuilder(
          org.utkuozdemir.sample2.protobuf.Many.getDefaultInstance());
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public org.utkuozdemir.sample2.protobuf.Many.Builder addManyBuilder(
        int index) {
      return getManyFieldBuilder().addBuilder(
          index, org.utkuozdemir.sample2.protobuf.Many.getDefaultInstance());
    }
    /**
     * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
     */
    public java.util.List<org.utkuozdemir.sample2.protobuf.Many.Builder> 
         getManyBuilderList() {
      return getManyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.utkuozdemir.sample2.protobuf.Many, org.utkuozdemir.sample2.protobuf.Many.Builder, org.utkuozdemir.sample2.protobuf.ManyOrBuilder> 
        getManyFieldBuilder() {
      if (manyBuilder_ == null) {
        manyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.utkuozdemir.sample2.protobuf.Many, org.utkuozdemir.sample2.protobuf.Many.Builder, org.utkuozdemir.sample2.protobuf.ManyOrBuilder>(
                many_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        many_ = null;
      }
      return manyBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.utkuozdemir.sample2.protobuf.One)
  }

  static {
    defaultInstance = new One(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.utkuozdemir.sample2.protobuf.One)
}

