// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: one_protos.proto

package org.utkuozdemir.sample2.protobuf;

public interface OneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.utkuozdemir.sample2.protobuf.One)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  java.util.List<org.utkuozdemir.sample2.protobuf.Many> 
      getManyList();
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  org.utkuozdemir.sample2.protobuf.Many getMany(int index);
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  int getManyCount();
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  java.util.List<? extends org.utkuozdemir.sample2.protobuf.ManyOrBuilder> 
      getManyOrBuilderList();
  /**
   * <code>repeated .org.utkuozdemir.sample2.protobuf.Many many = 2;</code>
   */
  org.utkuozdemir.sample2.protobuf.ManyOrBuilder getManyOrBuilder(
      int index);
}
