// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: one_protos.proto

package org.utkuozdemir.sample2.protobuf;

public final class OneProtos {
  private OneProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_utkuozdemir_sample2_protobuf_Many_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_utkuozdemir_sample2_protobuf_Many_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_utkuozdemir_sample2_protobuf_One_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_utkuozdemir_sample2_protobuf_One_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020one_protos.proto\022 org.utkuozdemir.samp" +
      "le2.protobuf\"\024\n\004Many\022\014\n\004name\030\001 \002(\t\"I\n\003On" +
      "e\022\014\n\004name\030\001 \002(\t\0224\n\004many\030\002 \003(\0132&.org.utku" +
      "ozdemir.sample2.protobuf.ManyB$\n org.utk" +
      "uozdemir.sample2.protobufP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_utkuozdemir_sample2_protobuf_Many_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_utkuozdemir_sample2_protobuf_Many_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_utkuozdemir_sample2_protobuf_Many_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_utkuozdemir_sample2_protobuf_One_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_utkuozdemir_sample2_protobuf_One_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_utkuozdemir_sample2_protobuf_One_descriptor,
        new java.lang.String[] { "Name", "Many", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
